name: New Issue Workflow
on:
  issues:
    types: [opened]

jobs:
  newIssueJob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Print Issue Title
        run: echo "New issue created: ${{ github.event.issue.title }}"

