name: info 
on: 
  issues:
    types: [opened,edited]
  push:
    branches:
      - master
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: info
        run: echo "${{ toJSON(github) }}"